# .github/workflows/pages.yml
name: Deploy Pages

on:
  push:
    branches: [ main ]   # <-- change to your default branch if not 'main'
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    # This environment name must be exactly 'github-pages'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      # REQUIRED: sets up the Pages build context
      - uses: actions/configure-pages@v5

      # Upload the folder that contains index.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      # REQUIRED: actually deploys the artifact to the Pages environment
      - id: deployment
        uses: actions/deploy-pages@v4
